[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_API_BASE_URL = "https://eventgenie-backend.vercel.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
